### ISSUE TITLE
Macro collision with HIP and nvcc backend

### ISSUE THREAD

**Issue by Rombur** [ORNL-CEES/kokkos#5]
HIP defines a macro `abort` in its nvcc backend which collides with the abort function defined in core/src/impl/Kokkos_Error.hpp (see [here](https://github.com/ORNL-CEES/kokkos/pull/2/files#diff-9765984e06a25bc65d63161eed041e3aR59))

**Comment by dalg24** [comment]
Fixed by 9b006f0d3be8707b30905c34274b7e61b7f81eda which made its way into `hip` when #2 was merged
